name: Detect Secrets (Yelp)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  detect-secrets:
    runs-on: ubuntu-latest

    env:
      # Ajusta exclusiones (regex) según tu repo
      DETECT_SECRETS_EXCLUDES: '(\/\.git\/|\/node_modules\/|\/target\/|\/build\/|\/dist\/|\/coverage\/|\/\\.secrets\.(baseline|json|diff|new)$)'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install detect-secrets
        run: |
          set -euxo pipefail
          python -V
          pip install --upgrade pip
          pip install "detect-secrets==1.5.0"
          detect-secrets --version || true

      - name: Run detect-secrets scan
        run: |
          set -euxo pipefail

          if [ -f ".secrets.baseline" ]; then
            echo "Using existing baseline (.secrets.baseline)"
            detect-secrets scan \
              --all-files \
              --exclude-files "${DETECT_SECRETS_EXCLUDES}" \
              --baseline .secrets.baseline \
              > .secrets.json
          else
            echo "No baseline present; scanning entire repo"
            detect-secrets scan \
              --all-files \
              --exclude-files "${DETECT_SECRETS_EXCLUDES}" \
              > .secrets.json
          fi

          # ----- Resumen con jq -----
          # Total de hallazgos
          count=$(jq '[.results[] | length] | add // 0' .secrets.json)
          echo "Possible secrets found: ${count}"

          # Hallazgos por tipo
          echo "Findings by type:"
          jq -r '
            .results
            | to_entries[]
            | .value[]
            | .type
          ' .secrets.json \
          | sort | uniq -c | sed 's/^/  - /' || true

          # Archivos afectados y cantidad
          echo "Files with findings:"
          jq -r '
            .results
            | to_entries[]
            | "[\(.value|length)] \(.key)"
          ' .secrets.json || true

          # Falla el job si count > 0
          if [ "${count}" -gt 0 ]; then
            exit 1
          fi

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detect-secrets-report
          path: .secrets.json
          if-no-files-found: warn
